site_name: TLT Finanças
site_description: Documentação do Projeto TLT Finanças
site_author: Grupo 3 - Tengo Lengo Tengo
site_url: https://mdsreq-fga-unb.github.io/REQ-2026.1-T02-TLF/

theme:
  name: material
  language: pt
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.expand
    - navigation.path
    - navigation.footer.prev_next
    - toc.follow
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: red
      accent: deep-orange
      toggle:
        icon: material/weather-night
        name: Alternar para modo escuro
    - scheme: slate
      primary: red
      accent: deep-orange
      toggle:
        icon: material/weather-sunny
        name: Alternar para modo claro

plugins:
  - search

nav:
  - Visão do Produto e Projeto:
    - 1-Cenário: visao/1-cenario.md
    - 2-Solução: visao/2-solucao.md
    - 3-Estratégias: visao/3-estrategias.md
    - 4-Engenharia de Requisitos: visao/4-engenharia-requisitos.md
    - 5-Cronograma: visao/5-cronograma.md
    - 6-Interação entre equipe e cliente: visao/6-interacao-equipe.md
    - 10.1-Unidade 1: visao/10-unidade-1.md
  - Entregas: entregas/apresentacao.md