import type { ComponentType } from 'react'
import {
  ArrowLeft,
  ArrowLeftRight,
  Banknote,
  BarChart3,
  Bell,
  Briefcase,
  Bus,
  Calendar,
  CalendarCheck,
  Car,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  CircleCheck,
  CircleDollarSign,
  Clapperboard,
  Clock,
  CreditCard,
  Delete,
  DollarSign,
  Dumbbell,
  Ellipsis,
  Folder,
  Gamepad2,
  Gift,
  GraduationCap,
  Hospital,
  House,
  Landmark,
  Luggage,
  Pill,
  Plane,
  Plus,
  Receipt,
  RefreshCw,
  RefreshCwOff,
  Repeat,
  Search,
  ShoppingBag,
  ShoppingCart,
  SkipForward,
  Tag,
  Trash2,
  TrendingUp,
  Undo2,
  Utensils,
  UtensilsCrossed,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react-native'

export type AppIconProps = {
  size?: number
  color?: string
  strokeWidth?: number
}

export type AppIcon = ComponentType<AppIconProps>

export const iconByKey = {
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  banknote: Banknote,
  'bar-chart': BarChart3,
  bell: Bell,
  briefcase: Briefcase,
  bus: Bus,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  car: Car,
  'chart-line': ChartLine,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-up-down': ChevronsUpDown,
  'circle-check': CircleCheck,
  'circle-dollar': CircleDollarSign,
  clapperboard: Clapperboard,
  clock: Clock,
  'credit-card': CreditCard,
  delete: Delete,
  'dollar-sign': DollarSign,
  dumbbell: Dumbbell,
  ellipsis: Ellipsis,
  folder: Folder,
  gamepad: Gamepad2,
  gift: Gift,
  'graduation-cap': GraduationCap,
  hospital: Hospital,
  house: House,
  landmark: Landmark,
  luggage: Luggage,
  pill: Pill,
  plane: Plane,
  plus: Plus,
  receipt: Receipt,
  'refresh-cw': RefreshCw,
  'refresh-cw-off': RefreshCwOff,
  repeat: Repeat,
  search: Search,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'skip-forward': SkipForward,
  tag: Tag,
  trash: Trash2,
  'trending-up': TrendingUp,
  undo: Undo2,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>

export type IconKey = keyof typeof iconByKey

export function resolveIcon(key: string): AppIcon {
  return iconByKey[key as IconKey] ?? Tag
}
