import type { ComponentType } from 'react'
import {
  AlarmClock,
  Clock3,
  AlertCircle,
  Archive,
  ArrowLeft,
  ArrowLeftRight,
  BarChart3,
  Banknote,
  Bell,
  Bike,
  BookOpen,
  Bookmark,
  Briefcase,
  Bus,
  Calendar,
  CalendarCheck,
  CalendarX,
  Camera,
  Car,
  Check,
  CircleCheck,
  CircleDollarSign,
  CircleUser,
  CircleX,
  Clapperboard,
  Cloud,
  Code2,
  Coins,
  Compass,
  Copy,
  CreditCard,
  Delete,
  DollarSign,
  Download,
  Dumbbell,
  Ellipsis,
  Eye,
  EyeOff,
  File,
  Filter,
  FilterX,
  Flag,
  Folder,
  Fuel,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Grid2x2,
  Headphones,
  Heart,
  HeartHandshake,
  HeartPulse,
  History,
  Hospital,
  House,
  Image,
  Info,
  KeyRound,
  Laugh,
  Leaf,
  Lightbulb,
  Link,
  List,
  Luggage,
  Mail,
  MapPin,
  MessageCircle,
  Palette,
  ThumbsUp,
  Mic,
  MoonStar,
  Music,
  Newspaper,
  Monitor,
  Pause,
  Pencil,
  Phone,
  PiggyBank,
  Pill,
  Plane,
  Rocket,
  Trophy,
  Truck,
  Play,
  Printer,
  Receipt,
  RefreshCw,
  RefreshCwOff,
  Repeat,
  Route,
  Search,
  Send,
  Settings,
  ShieldCheck,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  SkipForward,
  Smile,
  Sparkles,
  Star,
  Store,
  Tag,
  TimerReset,
  ToggleLeft,
  TrainFront,
  Trash2,
  TriangleAlert,
  TrendingUp,
  Undo2,
  Upload,
  User,
  UserPlus,
  Utensils,
  UtensilsCrossed,
  Video,
  Volume2,
  Wallet,
  Wifi,
  Wrench,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react-native'

export type AppIconProps = {
  size?: number
  color?: string
  strokeWidth?: number
}

export type AppIcon = ComponentType<AppIconProps>

export const iconByKey = {
  'alert-circle': AlertCircle,
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  alarm: AlarmClock,
  'alarm-clock': AlarmClock,
  archive: Archive,
  airplane: Plane,
  'arrow-clockwise': RefreshCw,
  'arrow-counter-clockwise': Undo2,
  banknote: Banknote,
  'currency-dollar': CircleDollarSign,
  'bar-chart': BarChart3,
  bell: Bell,
  bike: Bike,
  book: BookOpen,
  bookmark: Bookmark,
  briefcase: Briefcase,
  browser: Monitor,
  bus: Bus,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  'calendar-x': CalendarX,
  camera: Camera,
  'camera-rotate': Camera,
  car: Car,
  chat: MessageCircle,
  'chart-bar': BarChart3,
  check: Check,
  'check-circle': CircleCheck,
  'circle-check': CircleCheck,
  'circle-dollar': CircleDollarSign,
  clapperboard: Clapperboard,
  cloud: Cloud,
  code: Code2,
  coins: Coins,
  compass: Compass,
  copy: Copy,
  card: CreditCard,
  'credit-card': CreditCard,
  delete: Delete,
  'dollar-sign': DollarSign,
  dumbbell: Dumbbell,
  download: Download,
  ellipsis: Ellipsis,
  envelope: Mail,
  eye: Eye,
  'eye-slash': EyeOff,
  file: File,
  'file-text': File,
  filter: Filter,
  funnel: Filter,
  'filter-x': FilterX,
  flag: Flag,
  folder: Folder,
  fuel: Fuel,
  gamepad: Gamepad2,
  gear: Settings,
  gift: Gift,
  globe: Globe,
  'graduation-cap': GraduationCap,
  heart: Heart,
  heartbeat: HeartPulse,
  'heart-pulse': HeartPulse,
  'hand-heart': HeartHandshake,
  headphones: Headphones,
  history: History,
  hospital: Hospital,
  laugh: Laugh,
  house: House,
  image: Image,
  info: Info,
  key: KeyRound,
  leaf: Leaf,
  lightbulb: Lightbulb,
  link: Link,
  list: List,
  luggage: Luggage,
  microphone: Mic,
  'map-pin': MapPin,
  music: Music,
  moon: MoonStar,
  newspaper: Newspaper,
  phone: Phone,
  'paper-plane': Send,
  pause: Pause,
  pencil: Pencil,
  'piggy-bank': PiggyBank, // Corrigido aqui
  pill: Pill,
  plane: Plane,
  rocket: Rocket,
  play: Play,
  printer: Printer,
  receipt: Receipt,
  'refresh-cw': RefreshCw,
  'refresh-cw-off': RefreshCwOff,
  repeat: Repeat,
  route: Route,
  search: Search,
  'shield-check': ShieldCheck,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
  'skip-forward': SkipForward, // Corrigido aqui
  smile: Smile,
  smiley: Smile,
  sparkles: Sparkles,
  'squares-four': Grid2x2, // Corrigido aqui
  'thumbs-up': ThumbsUp, // Corrigido aqui
  star: Star,
  trophy: Trophy,
  swatches: Palette,
  storefront: Store,
  store: Store,
  truck: Truck,
  tag: Tag,
  timer: TimerReset,
  'toggle-left': ToggleLeft,
  train: TrainFront,
  trash: Trash2,
  'triangle-alert': TriangleAlert,
  'trending-up': TrendingUp,
  undo: Undo2,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  upload: Upload,
  'user-circle': CircleUser,
  user: User,
  'user-plus': UserPlus,
  video: Video,
  'video-camera': Video,
  volume: Volume2,
  speaker: Volume2,
  wallet: Wallet,
  wifi: Wifi,
  wrench: Wrench,
  x: X,
  clock: Clock3,
  'x-circle': CircleX,
  zap: Zap,
} satisfies Record<string, LucideIcon>

export type IconKey = keyof typeof iconByKey

export function resolveIcon(key: string): AppIcon {
  return iconByKey[key as IconKey] ?? Tag
}
