import type { ComponentType } from 'react'
import {
  AlertCircle,
  ArrowLeft,
  ArrowLeftRight,
  Banknote,
  BarChart3,
  Bell,
  Bike,
  Briefcase,
  Bus,
  Calendar,
  CalendarCheck,
  CalendarX,
  Car,
  ChartLine,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  CircleCheck,
  CircleDollarSign,
  Clapperboard,
  Coins,
  Clock,
  CreditCard,
  Delete,
  DollarSign,
  Dumbbell,
  Ellipsis,
  FileText,
  Filter,
  FilterX,
  Folder,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Heart,
  HeartPulse,
  History,
  Hospital,
  House,
  Landmark,
  Laugh,
  Luggage,
  Newspaper,
  Pencil,
  PiggyBank,
  Pill,
  Plane,
  Plus,
  Receipt,
  RefreshCw,
  RefreshCwOff,
  Repeat,
  Route,
  Search,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  SkipForward,
  Smile,
  Tag,
  TrainFront,
  Trash2,
  TriangleAlert,
  TrendingUp,
  Undo2,
  Utensils,
  UtensilsCrossed,
  Wallet,
  X,
  Zap,
  type LucideIcon,
} from 'lucide-react-native'

export type AppIconProps = IconProps
export type AppIconComponent = ComponentType<IconProps>

export const iconByKey = {
  'alert-circle': AlertCircle,
  'arrow-left': ArrowLeft,
  'arrow-left-right': ArrowLeftRight,
  banknote: Banknote,
  'bar-chart': BarChart3,
  bell: Bell,
  bike: Bike,
  briefcase: Briefcase,
  bus: Bus,
  calendar: Calendar,
  'calendar-check': CalendarCheck,
  'calendar-x': CalendarX,
  car: Car,
  'chart-line': ChartLine,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-up-down': ChevronsUpDown,
  'circle-check': CircleCheck,
  'circle-dollar': CircleDollarSign,
  clapperboard: Clapperboard,
  coins: Coins,
  clock: Clock,
  'credit-card': CreditCard,
  delete: Delete,
  'dollar-sign': DollarSign,
  dumbbell: Dumbbell,
  ellipsis: Ellipsis,
  'file-text': FileText,
  filter: Filter,
  'filter-x': FilterX,
  folder: Folder,
  fuel: Fuel,
  gamepad: Gamepad2,
  gift: Gift,
  'graduation-cap': GraduationCap,
  heart: Heart,
  'heart-pulse': HeartPulse,
  history: History,
  hospital: Hospital,
  house: House,
  landmark: Landmark,
  laugh: Laugh,
  luggage: Luggage,
  newspaper: Newspaper,
  pencil: Pencil,
  'piggy-bank': PiggyBank,
  pill: Pill,
  plane: Plane,
  plus: Plus,
  receipt: Receipt,
  'refresh-cw': RefreshCw,
  'refresh-cw-off': RefreshCwOff,
  repeat: Repeat,
  route: Route,
  search: Search,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  'shopping-cart': ShoppingCart,
  'skip-forward': SkipForward,
  smile: Smile,
  tag: Tag,
  train: TrainFront,
  trash: Trash2,
  'triangle-alert': TriangleAlert,
  'trending-up': TrendingUp,
  undo: Undo2,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  wallet: Wallet,
  x: X,
  zap: Zap,
} satisfies Record<string, LucideIcon>

export type IconKey = keyof typeof iconByKey

export function resolveIcon(key: string): AppIconComponent {
  return iconByKey[key as IconKey] ?? Tag
}